# Generated by Django 4.2.6 on 2023-10-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_clubbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='clubbooking',
            name='total_days',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
