# Generated by Django 4.2.6 on 2023-10-31 12:07

import authentication.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='profile',
            field=models.FileField(upload_to=authentication.helpers.custom_file_name),
        ),
    ]
