# Generated by Django 4.2.6 on 2023-10-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_gallery_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='profile',
            new_name='gallry_photo',
        ),
    ]
