# Generated by Django 4.2.6 on 2023-11-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_catagory_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='date_added',
            field=models.DateTimeField(auto_now=True)
        ),
    ]
