# Generated by Django 4.2.6 on 2023-11-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_gallery_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='date_added',
        ),
    ]
