# Generated by Django 4.2.6 on 2023-11-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_gallery_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='gallry_photo',
            new_name='gallery_photo',
        ),
    ]
