# Generated by Django 4.2.6 on 2023-11-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_gallery_delete_galleryphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
