# Generated by Django 4.2.6 on 2023-11-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubbooking',
            name='from_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clubbooking',
            name='to_date',
            field=models.CharField(max_length=10),
        ),
    ]
