# Generated by Django 4.2.6 on 2023-11-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_clubbooking_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubbooking',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clubbooking',
            name='to_date',
            field=models.DateField(),
        ),
    ]
