# Generated by Django 4.2.6 on 2023-11-02 09:53

import authentication.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_clubbooking_from_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(default='default-profile.png', upload_to=authentication.helpers.custom_file_name)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
