# Generated by Django 4.2.6 on 2023-11-02 11:09

import authentication.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_gallery_file_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergency_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emergency_photo', models.FileField(default='default-event.png', upload_to=authentication.helpers.custom_file_name)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
