# Generated by Django 4.2.6 on 2023-10-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersmodel',
            name='otp',
            field=models.CharField(blank=True, default='908756', max_length=10),
        ),
    ]
